version: "3"

services:
  graphdb:
    container_name: graphdb
    build:
      context: graphdb-docker
      dockerfile: Dockerfile
      args:
        version: 10.1.3
    restart: unless-stopped
    environment: 
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports: 
      - 7200:7200
      - 7300:7300
    volumes:
      - ./graphdb-docker/graphdb-data:/opt/graphdb/home
  backend:
    container_name: backend
    build:
      context: udapi-java
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 8081:8081
    volumes:
      - ./resources:/app/resources
  frontend:
    container_name: frontend
    build:
      context: rutui
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
